# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popote',
            old_name='auteur',
            new_name='quantite',
        ),
    ]
